#! /bin/bash
#build dep for the program
# to be added
# build dep
# sudo apt-get install libtool

CUR_DIR=$(pwd)
LIB_PREFIX=${CUR_DIR}/.local/

mkdir -p ${LIB_PREFIX}

LIBCONFIG_VER=1.4.9
LIBCONFIG_NAME=libconfig-${LIBCONFIG_VER}

BDB_VER=5.1.29
BDB_NAME=db-${BDB_VER}

LIBEVENT_VER=2.0.22
LIBEVENT_NAME=libevent-$LIBEVENT_VER-stable
LIBEVENT_TAR=${LIBEVENT_NAME}.tar.gz
LIBEVENT_URL=https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/$LIBEVENT_TAR


if [ ! -d "dep-lib" ];then
    mkdir dep-lib
fi
cd dep-lib

if [ ! -f "$LIBEVENT_TAR" ]; then
	wget $LIBEVENT_URL
fi

if [ ! -d "$LIBEVENT_NAME" ]; then
	tar -xvf $LIBEVENT_TAR
fi

cd $LIBEVENT_NAME
pwd
./configure --prefix=${LIB_PREFIX}
make
make install;
cd ..

if [ ! -f "${LIBCONFIG_NAME}.tar.gz" ];then
    wget http://www.hyperrealm.com/libconfig/${LIBCONFIG_NAME}.tar.gz
fi


if [ ! -d "${LIBCONFIG_NAME}" ];then
    tar -xvf ${LIBCONFIG_NAME}.tar.gz
fi

cd ${LIBCONFIG_NAME}
pwd
./configure --prefix=${LIB_PREFIX}
make;
make install;
cd ..

if [ ! -f "${BDB_NAME}.tar.gz" ];then
    wget http://download.oracle.com/berkeley-db/${BDB_NAME}.tar.gz
fi

if [ ! -d "${BDB_NAME}" ];then
    tar -xvf ${BDB_NAME}.tar.gz
fi

cd ${BDB_NAME}
pwd
cd build_unix
../dist/configure --prefix=${LIB_PREFIX}
make;
make install;
cd ..
cd ..

cd ..
