#! /bin/bash

VER=3.6
cd /home/wangcheng/mongoose
if [ ! -f mongoose-$VER.tgz ]; then
    wget http://mongoose.googlecode.com/files/mongoose-$VER.tgz
fi
tar zxvf mongoose-$VER.tgz
cd mongoose
make linux
