#!/bin/bash
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
#run master in localhost
cd $RDMA_ROOT/apps/redis/install
./redis-server ./redis.conf &

#run slaves 
ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host1) "$RDMA_ROOT/apps/redis/install/redis-server $RDMA_ROOT/apps/redis/install/redis-slave.conf &" &
ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host2) "$RDMA_ROOT/apps/redis/install/redis-server $RDMA_ROOT/apps/redis/install/redis-slave.conf &" &

