#!/bin/bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

cd $RDMA_ROOT/apps/pgsql/install
./bin/pg_ctl start -D ./data

ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host1) "$RDMA_ROOT/apps/pgsql/install/bin/pg_ctl start -D $RDMA_ROOT/apps/pgsql/install/data" &
ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host2) "$RDMA_ROOT/apps/pgsql/install/bin/pg_ctl start -D $RDMA_ROOT/apps/pgsql/install/data" 

