#! /bin/bash
#build dep for the program

CUR_DIR=$(pwd)
LIB_PREFIX=${CUR_DIR}/.local/

mkdir -p ${LIB_PREFIX}

LIBCONFIG_VER=1.4.9
LIBCONFIG_NAME=libconfig-${LIBCONFIG_VER}

LIBEV_VER=4.15
LIBEV_NAME=libev-${LIBEV_VER}

BDB_VER=5.1.29
BDB_NAME=db-${BDB_VER}

if [ ! -d "dep-lib" ];then
# True if dep-lib exists and is a directory.
    mkdir dep-lib
fi
cd dep-lib

if [ ! -f "${LIBCONFIG_NAME}.tar.gz" ];then
# True if ${LIBCONFIG_NAME}.tar.gz exists and is an ordinary file. 
    wget http://www.hyperrealm.com/libconfig/${LIBCONFIG_NAME}.tar.gz
fi

if [ ! -d "${LIBCONFIG_NAME}" ];then
    tar -xvf ${LIBCONFIG_NAME}.tar.gz
fi

cd ${LIBCONFIG_NAME}
pwd
./configure --prefix=${LIB_PREFIX}
make;
make install;
cd ..


if [ ! -f "${LIBEV_NAME}.tar.gz" ];then
    wget http://dist.schmorp.de/libev/Attic/{LIBEV_NAME}.tar.gz
fi

if [ ! -d "${LIBEV_NAME}" ];then
    tar -xvf ${LIBEV_NAME}.tar.gz
fi

cd ${LIBEV_NAME}
pwd
./configure --prefix=${LIB_PREFIX}
make;
make install;
cd ..


if [ ! -f "${BDB_NAME}.tar.gz" ];then
    wget http://download.oracle.com/berkeley-db/${BDB_NAME}.tar.gz
fi

if [ ! -d "${BDB_NAME}" ];then
    tar -xvf ${BDB_NAME}.tar.gz
fi

cd ${BDB_NAME}
pwd
cd build_unix
../dist/configure --prefix=${LIB_PREFIX}
make;
make install;
cd ..
cd ..

cd ..
