#!/bin/bash
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ ! -f master.zip ]
then
    wget --no-check-certificate https://github.com/ideawu/ssdb/archive/master.zip
fi
unzip master
cd ssdb-master
make

LOCAL_IP=$(cat $RDMA_ROOT/apps/env/local_host)

sed -i "s/ip: 127.0.0.1/ip: 0.0.0.0/g" ./ssdb.conf
sed -i "s/port: 8888/port: 28888/g" ./ssdb.conf
#sed -i "s/#id: svc_2/id: svc_1/g" ./ssdb.conf
#sed -i "s/#type/type/g" ./ssdb.conf
#sed -i "s/#host: localhost/host: $LOCAL_IP/g" ./ssdb.conf
#sed -i "s/port: 8888/port: 7004/g" ./ssdb.conf

cd ..
scp -rp ./ssdb-master $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host1):$RDMA_ROOT/apps/ssdb
scp -rp ./ssdb-master $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host2):$RDMA_ROOT/apps/ssdb
scp -rp ./ssdb-master $LOGNAME@$(cat $RDMA_ROOT/apps/env/test_host):$RDMA_ROOT/apps/ssdb

