#!/bin/bash
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

cd $RDMA_ROOT/apps/redis/ssdb-master
./ssdb-server -d ./ssdb.conf

#run slaves 
ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host1) "$RDMA_ROOT/apps/ssdb/ssdb-master/ssdb-server -d $RDMA_ROOT/apps/ssdb/ssdb-master/ssdb.conf" &
ssh $LOGNAME@$(cat $RDMA_ROOT/apps/env/remote_host2) "$RDMA_ROOT/apps/ssdb/ssdb-master/ssdb-server -d $RDMA_ROOT/apps/ssdb/ssdb-master/ssdb.conf" &
