#!/bin/bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

REDIS_VER=3.0.7
cd $RDMA_ROOT/apps/redis
mkdir -p $RDMA_ROOT/apps/redis/install

if [ ! -f redis-$REDIS_VER.tar.gz ]; then
    wget http://download.redis.io/releases/redis-$REDIS_VER.tar.gz
fi

tar xzf redis-$REDIS_VER.tar.gz
rm redis-$REDIS_VER.tar.gz
cd redis-$REDIS_VER
make
cd src
cp redis-benchmark redis-check-aof redis-check-dump redis-cli redis-server mkreleasehdr.sh $RDMA_ROOT/apps/redis/install
cd ..
cp redis.conf $RDMA_ROOT/apps/redis/install
cd ..
rm -rf redis-$REDIS_VER
LOCAL_HOST=$(cat $RDMA_ROOT/apps/env/local_host)
LOCAL_IP=${LOCAL_HOST#*@}
sed "s/# slaveof <masterip> <masterport>/slaveof $LOCAL_IP 6379/g" ./install/redis.conf  > ./install/redis-slave.conf
#cd ..

scp -rp ./install $(cat $RDMA_ROOT/apps/env/remote_host1):$RDMA_ROOT/apps/redis
scp -rp ./install $(cat $RDMA_ROOT/apps/env/remote_host2):$RDMA_ROOT/apps/redis
