#!/bin/bash

# MONITOR is a debugging command that streams back every command processed by the Redis server.
# It can help in understanding what is happening to the database.
# $ redis-cli monitor
# 1339518083.107412 [0 127.0.0.1:60866] "keys" "*"
# 1339518087.877697 [0 127.0.0.1:60866] "dbsize"
# 1339518090.420270 [0 127.0.0.1:60866] "set" "x" "6"
# 1339518096.506257 [0 127.0.0.1:60866] "get" "x"
# 1339518099.363765 [0 127.0.0.1:60866] "del" "x"
# 1339518100.544926 [0 127.0.0.1:60866] "get" "x"


# Measuring latency
# showLatencyReport in redis-benchmark.c
# for (i = 0; i < config.requests; i++) {
#     # print config.latency
# }


################################ SNAPSHOTTING  ################################
#
# Save the DB on disk:
#
#   save <seconds> <changes>
#
#   Will save the DB if both the given number of seconds and the given
#   number of write operations against the DB occurred.
#
#   In the example below the behaviour will be to save:
#   after 900 sec (15 min) if at least 1 key changed
#   after 300 sec (5 min) if at least 10 keys changed
#   after 60 sec if at least 10000 keys changed
#
#   Note: you can disable saving at all commenting all the "save" lines.

# save 900 1
# save 300 10
# save 60 10000
