#!/bin/bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

cd $RDMA_ROOT/apps/mongodb

SERVER_ONE_IP=$(cat $RDMA_ROOT/apps/env/local_host)
SERVER_ONE=$LOGNMAE@$SERVER_ONE_IP
SERVER_TWO_IP=$(cat $RDMA_ROOT/apps/env/remote_host1)
SERVER_TWO=$LOGNMAE@$SERVER_TWO_IP
SERVER_THR_IP=$(cat $RDMA_ROOT/apps/env/remote_host2)
SERVER_THR=$LOGNMAE@$SERVER_THR_IP

$RDMA_ROOT/apps/mongodb/install/bin/mongod --config $RDMA_ROOT/apps/mongodb/install/mongodb.conf

ssh $SERVER_TWO "$RDMA_ROOT/apps/mongodb/install/bin/mongod --config $RDMA_ROOT/apps/mongodb/install/mongodb.conf"

ssh $SERVER_THR "$RDMA_ROOT/apps/mongodb/install/bin/mongod --config $RDMA_ROOT/apps/mongodb/install/mongodb.conf"

cd ycsb-mongodb

./bin/ycsb load mongodb -P ./workloads/workloadc -p mongodb.url=mongodb://$SERVER_ONE_IP:27017 
./bin/ycsb run mongodb -P ./workloads/workloadc -p mongodb.url=mongodb://$SERVER_ONE_IP:27017 

